server:
  port: 7529
  servlet:
    context-path: /api
    multipart:
      enabled: true
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://xxx:13306/mikania_micrantha_kunth
    username: root
    password: xxx
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  redis:
    port: 7001
    host: xxx
    database: 0
    password: xxx
oss:
  accessKeyId: xxx
  accessKeySecret: xxx
  endpoint: oss-cn-guangzhou.aliyuncs.com
  maxConnections: 1024
  maxErrorRetry: 5
  idleConnectionTime: 100000
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
